spring:
  profiles:
    active: ${targetEnv}
    include: application-${spring.profiles.active}.yml
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
ta.rates:    
    intra-day-brokerage-cost: 20.00
    brokerage-cost:  0.00
    stt-rate: 0.001
    intra-day-sttRate:  0.00025
    demat:  0.00
    intra-day-stamp-duty-rate:  0.0001
    stamp-duty-rate:  0.0001
    intra-day-exchange-fee:  0.0000015
    exchange-fee:  0.0000015
    intra-day-sebi-fee:  0.0000325
    sebi-fee:  0.0000325
    gst-rate:  0.18
    version: "2022-12-31"